INSERT INTO global_definitions (id, label, definition_value, category) VALUES
(nextval('global_definitions_seq'), 'gluten', 'Glutenunverträglichkeit / Zöliakie', 0),
(nextval('global_definitions_seq'), 'laktose', 'Laktoseintoleranz', 0),
(nextval('global_definitions_seq'), 'fruktose', 'Fruktoseintoleranz', 0),
(nextval('global_definitions_seq'), 'histamin', 'Histaminintoleranz', 0),
(nextval('global_definitions_seq'), 'milch', 'Milchallergie', 0),
(nextval('global_definitions_seq'), 'ei', 'Hühnerei-Allergie', 0),
(nextval('global_definitions_seq'), 'erdnuss', 'Erdnussallergie', 0),
(nextval('global_definitions_seq'), 'nuesse', 'Schalenfruchtallergie / Nussallergie', 0),
(nextval('global_definitions_seq'), 'mandel', 'Mandelallergie', 0),
(nextval('global_definitions_seq'), 'haselnuss', 'Haselnussallergie', 0),
(nextval('global_definitions_seq'), 'walnuss', 'Walnussallergie', 0),
(nextval('global_definitions_seq'), 'cashew', 'Cashewallergie', 0),
(nextval('global_definitions_seq'), 'pistazie', 'Pistazienallergie', 0),
(nextval('global_definitions_seq'), 'sesam', 'Sesamallergie', 0),
(nextval('global_definitions_seq'), 'soja', 'Sojaallergie', 0),
(nextval('global_definitions_seq'), 'weizen', 'Weizenallergie', 0),
(nextval('global_definitions_seq'), 'fisch', 'Fischallergie', 0),
(nextval('global_definitions_seq'), 'krebstiere', 'Krebstierallergie', 0),
(nextval('global_definitions_seq'), 'weichtiere', 'Weichtierallergie', 0),
(nextval('global_definitions_seq'), 'sellerie', 'Sellerieallergie', 0),
(nextval('global_definitions_seq'), 'senf', 'Senfallergie', 0),
(nextval('global_definitions_seq'), 'lupine', 'Lupinenallergie', 0),
(nextval('global_definitions_seq'), 'schwefeldioxid', 'Schwefeldioxid-/Sulfitempfindlichkeit', 0),
(nextval('global_definitions_seq'), 'steinobst', 'Allergie auf Steinobst', 0),
(nextval('global_definitions_seq'), 'zitrus', 'Zitrusfruchtallergie', 0),
(nextval('global_definitions_seq'), 'honig', 'Honigallergie / Unverträglicheit', 0),
(nextval('global_definitions_seq'), 'pollen', 'Pollenallergie', 1),
(nextval('global_definitions_seq'), 'hausstaub', 'Hausstaubmilbenallergie', 1),
(nextval('global_definitions_seq'), 'tierhaare', 'Tierhaarallergie', 1),
(nextval('global_definitions_seq'), 'insektengift', 'Insektengiftallergie', 1),
(nextval('global_definitions_seq'), 'latex', 'Latexallergie', 1),
(nextval('global_definitions_seq'), 'schimmel', 'Schimmelpilzallergie', 1),
(nextval('global_definitions_seq'), 'medikamente', 'Medikamentenallergie', 1),
(nextval('global_definitions_seq'), 'penicillin', 'Penicillinallergie', 1),
(nextval('global_definitions_seq'), 'sonne', 'Sonnenallergie', 1),
(nextval('global_definitions_seq'), 'parfum', 'Duftstoffallergie', 1),
(nextval('global_definitions_seq'), 'nickel', 'Nickelallergie', 1);